# Configuración de JWT
jwt:
  secret: "miclavesupersecretamuysegura1234567890abcdefghijklmnopqrstuvwxyz"  # Clave de 64 caracteres
  expiration-ms: 86400000  # 24 horas en milisegundos

# Configuración de Spring
spring:
  # Configuración de seguridad
  security:
    user:
      name: admin
      password: "$2a$10$XOL9NkPQs8o7GPLRgWjwQ..KcoU7ugzT9bzHimUKNUIRElI47IK9e"  # password123
      roles: ADMIN

  # Configuración de base de datos
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://client-managemet.cfkgwx0qfo1z.us-east-1.rds.amazonaws.com:3306/client-management}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:NUAhb5pDFiNvON3fXuTs}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate  # Mejor que 'none' para validar esquema
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Configuración de Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history
    validate-on-migrate: true