CREATE TABLE clients (
  id BIGINT NOT NULL AUTO_INCREMENT,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  age INT NOT NULL,
  birth_date DATE NOT NULL,
  created_at DATETIME NOT NULL,
  PRIMARY KEY (id)
);